version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cci-sam-currency"
s3_bucket = "mayoct-sam-moneyexchange"
s3_prefix = "cci-sam-currency"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
