AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  CCI-SAM-Currency

  Sample SAM Template for CCI-SAM-Currency

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ConvertCurrencyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ConvertCurrency:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: ./
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ConvertCurrencyApi:
    Description: "API Gateway endpoint URL for Prod stage for Convert Currency function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/currency/"
  ConvertCurrencyFunction:
    Description: "Convert Currency Lambda Function ARN"
    Value: !GetAtt ConvertCurrencyFunction.Arn
  ConvertCurrencyFunctionIamRole:
    Description: "Implicit IAM Role created for Convert Currency function"
    Value: !GetAtt ConvertCurrencyFunctionRole.Arn
