version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@3.1.0
  slack: circleci/slack@4.3.0

workflows:
  my_workflow_for_currency:
    jobs:
      - build_api:
          context: aws
      - test_api:
          context: aws
          requires:
            - build_api
      - deploy_api:
          context: aws
          requires:
            - test_api
      - notify_on_fail:
          context: slack
          requires:
            - build_api
            - test_api
            - deploy_api
      - notify_on_pass:
          context: slack
          requires:
            - deploy_api

jobs:
  build_api:
    executor: sam/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm install
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - sam/install
      - sam/build:
          template: template.yaml
      - persist_to_workspace:
          root: ~/project/.aws-sam
          paths:
            - build
            - build.toml
  test_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/.aws-sam
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - sam/install
      - run:
          command: |
            npm install
            mkdir reports      
      - run:
          command: npx nyc --silent npx mocha ./test/*.test.js --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./reports/mocha/test-results.xml
      - store_test_results:
          path: ./reports
  deploy_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/.aws-sam
      - sam/install
      - sam/deploy:
          stack-name: cci-sam-currency
          s3-bucket: mayoct-sam-moneyexchange
  notify_on_fail:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  notify_on_pass:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
