version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0
  slack: circleci/slack@4.3.0

workflows:
  my_workflow_for_currency:
    jobs:
      - build_api:
          context: aws
      - test_api:
          context: aws
          requires:
            - build_api
      - deploy_api:
          context: aws
          requires:
            - test_api
      - notify_on_fail:
          context: slack
          requires:
            - build_api
            - deploy_api
      - notify_always:
          context: slack
          requires:
            - deploy_api

jobs:
  build_api:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam build
      - persist_to_workspace:
          root: /home/circleci/project/.aws-sam
          paths:
            - build
            - build.toml
  test_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/.aws-sam
      - sam/install
      - run:
          command: |
            cd currency
            npm install
            npm test
  deploy_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/.aws-sam
      - sam/install
      - run: sam deploy --no-fail-on-empty-changeset
  notify_on_fail:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  notify_always:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
