version: "2.1"

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

jobs:
  build_api:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam build
      - persist_to_workspace:
          root: /home/circleci/project/.aws-sam
          paths:
            - build
            - build.toml
  test_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/.aws-sam
      - sam/install
      - run:
          command: |
            cd currency
            npm init
            npm test
  deploy_api:
    executor: sam/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/.aws-sam
      - sam/install
      - run: sam deploy

workflows:
  my-workflow:
    jobs:
      - build_api:
          context: aws
      - test_api:
          context: aws
          requires:
            - build_api
      - deploy_api:
          context: aws
          requires:
            - test_api
